---
name: CD
on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name == github.event.repository.default_branch }}
jobs:
  release:
    name: Release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate bot token
        id: bot-token
        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        with:
          app-id: ${{ vars.CICD_APP_ID }}
          private-key: ${{ secrets.CICD_PRIVATE_KEY }}
      - name: Cut release
        id: release
        uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4.1.3
        with:
          token: ${{ steps.bot-token.outputs.token }}
          target-branch: ${{ github.ref_name }}
    outputs:
      created: ${{ steps.release.outputs.release_created || '' }}
      tag: ${{ steps.release.outputs.tag_name }}
      tag-major: v${{ steps.release.output.major }}
      tag-minor: v${{ steps.release.output.major }}.${{ steps.release.outputs.minor }}
  vars:
    name: Fetch variables resolved during CI
    needs:
      - release
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.vars.outputs.json }}
    steps:
      - name: Download variables file
        uses: dawidd6/action-download-artifact@80620a5d27ce0ae443b965134db88467fc607b43 # v7
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: vars
      - name: Load variables file
        id: vars
        shell: bash
        run: |
          jq --compact-output . vars.json | xargs printf json=%s\\n >>"$GITHUB_OUTPUT"
          rm -f vars.json
  publish:
    name: Publish
    needs:
      - vars
      - release
    strategy:
      fail-fast: true
      matrix:
        os: ${{ fromJSON(needs.vars.outputs.json).runner-os }}
    if: ${{ needs.release.outputs.created }}
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
    steps:
      - name: Generate bot token
        id: bot-token
        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        with:
          app-id: ${{ vars.CICD_APP_ID }}
          private-key: ${{ secrets.CICD_PRIVATE_KEY }}
      - name: Fetch bot ID
        id: bot-id
        shell: bash
        run: |
          gh api "/users/$bot_username" --jq .id | xargs printf user-id=%s\\n >>"$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.bot-token.outputs.token }}
          bot_username: ${{ steps.bot-token.outputs.app-slug }}[bot]
      - name: Check out repository
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ steps.bot-token.outputs.token }}
      - name: Download `/nix` tarballs
        uses: dawidd6/action-download-artifact@80620a5d27ce0ae443b965134db88467fc607b43 # v7
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: tarballs-${{ runner.os }}-${{ runner.arch }}
      - name: Attach `/nix` tarballs to the GitHub release
        shell: bash
        run: |
          gh release upload "$tag" lix-*.tar.*
          rm -f lix-*.tar.*
        env:
          GH_TOKEN: ${{ steps.bot-token.outputs.token }}
          tag: ${{ needs.release.outputs.tag }}
      - name: Tag major and minor versions
        if: ${{ steps.release.outputs.created }}
        shell: bash
        run: |
          for tag in "$tag_major" "$tag_minor"; do
            git tag -d "$tag" ${{ runner.debug && '' || '>/dev/null 2>&1' }} || :
            git tag -a "$tag" -m "Release $tag â†’ $tag_full"
            git push origin :"$tag" ${{ runner.debug && '' || '>/dev/null 2>&1' }} || :
            git push origin "$tag"
          done
        env:
          GIT_AUTHOR_NAME: ${{ steps.bot-token.outputs.app-slug }}[bot]
          GIT_AUTHOR_EMAIL: ${{ steps.bot-id.outputs.user-id }}+${{ steps.bot-token.outputs.app-slug }}[bot]@noreply.users.github.com
          GIT_COMMITTER_NAME: ${{ steps.bot-token.outputs.app-slug }}[bot]
          GIT_COMMITTER_EMAIL: ${{ steps.bot-id.outputs.user-id }}+${{ steps.bot-token.outputs.app-slug }}[bot]@noreply.users.github.com
          tag_full: ${{ needs.release.outputs.tag }}
          tag_major: ${{ needs.release.outputs.tag-major }}
          tag_minor: ${{ needs.release.outputs.tag-minor }}
      - name: Mark release PR as published
        shell: bash
        run: |
           gh pr list --search "$head_sha"' is:merged label:"autorelease: tagged" sort:created-desc' --limit 1 --json number --jq '.[0].number' |
              xargs -I {} -- gh pr edit {} --add-label 'autorelease: published' --remove-label 'autorelease: tagged'
        env:
          GH_TOKEN: ${{ steps.bot-token.outputs.token }}
          head_sha: ${{ steps.checkout.outputs.commit }}
